### ISSUE TITLE
Replace Atmega4809

### ISSUE THREAD

**Issue by cnn123666** [CensoredUsername/NVGM#1]
hello

Thank you for this great project. Please forgive me as a novice programmer, it is not easy to buy Arduino Nano Every in my area. So I want to know whether Ledstripesplitter can be ported to Raspberry Pi Pico, Adafruit Feather M0, or STM32 platform. I think they perform better and cost less

**Comment by CensoredUsername** [comment]
The choice for the Arduino nano every was simply that it was the cheapest ready to go solution available for me here. It is perfectly possible to do it with another chip, as long as it can manage the required timings. To do this on the Atmega 4809 required the algorithm core to be completely written in assembly, so it will require a rewrite if trying to do the same on other architectures.

**Comment by cnn123666** [comment]
Thank you for your answer. Assembly language is still very difficult for beginners and I need to learn more
